# Informazioni di base
title: "Ombre e Percorsi"
description: "Tracce di luoghi, storie e persone"
author: "Pietro"
email: pbarale00@gmail.com
baseurl: "/OmbrePercorsi"
url: "https://pietro00b.github.io"
github_username: pietro00b

# Configurazione del tema
highlighter: rouge
markdown: kramdown
paginate: 5
paginate_path: "/pagina/:num/"

# Plugin
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Configurazione della collezione storie
collections:
  storie:
    output: true
    permalink: /:collection/:name/

# Layout predefiniti
defaults:
  - scope:
      path: ""
      type: "storie"
    values:
      layout: "storia"
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Configurazione social
social:
  - name: GitHub
    icon: github
    username: pietro00b
    url: https://github.com/pietro00b
  - name: Instagram
    icon: instagram
    username: 
    url: 

# Dettagli header
header_pages:
  - about.md
  - archivio.md
  - galleria.md
  - contatti.md

# Configurazione dei post
show_excerpts: true
excerpt_separator: <!--more-->
